[package]
org = "user"
name = "http_access_log_service"
version = "0.1.0"
distribution = "2201.2.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org="ballerina"
name="http"
repository="local"
version="2.4.2"
